import { api, data, ui, input, select, message, routeButton, confirmFa, tr} from './common.mjs'

const CSS=`
.cms-appearance-center{display:grid;gap:14px;direction:inherit}.cms-theme-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.cms-theme-toolbar .grow{flex:1}.cms-theme-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.cms-theme-card{border:1px solid var(--p-surface-200,#e5e7eb);border-radius:16px;padding:14px;display:grid;gap:10px;background:var(--p-surface-0,#fff)}.cms-theme-card.active{outline:2px solid var(--p-primary-300,#a5b4fc);outline-offset:1px}.cms-theme-card.blocked{border-color:var(--p-red-200,#fecaca)}.cms-theme-cover{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;background:var(--p-surface-100,#f3f4f6)}.cms-theme-no-preview{display:grid;place-items:center;align-content:center;gap:7px;opacity:.72}.cms-theme-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.cms-theme-meta{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.cms-theme-details{display:grid;gap:6px;font-size:12px}.cms-theme-details code{direction:ltr;text-align:left;overflow-wrap:anywhere}.cms-theme-issues{display:grid;gap:4px;padding:9px;border-radius:10px;background:var(--p-red-50,#fef2f2);color:var(--p-red-700,#b91c1c);font-size:12px}.cms-theme-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.cms-theme-empty{padding:30px;text-align:center;opacity:.7}@media(max-width:640px){.cms-theme-grid{grid-template-columns:1fr}.cms-theme-toolbar>*{width:100%}.cms-theme-toolbar .grow{display:none}}
`

function hasAbility(ability){const granted=data().currentUser?.abilities||[];return granted.includes('*')||granted.includes(ability)||granted.some(x=>typeof x==='string'&&x.endsWith('.*')&&ability.startsWith(x.slice(0,-1)))}
function safeCover(value){const v=String(value||'').trim();return /^(https?:\/\/|\/)/i.test(v)?v:''}
function requirementLabel(item){const req=item?.cms?.requires||{};return Object.entries(req).map(([k,v])=>`${k} ${v}`).join(' · ')}

export function createComponent(host){
  const{h,LPage,LPanel,LButton,LBadge,LStatCard}=host
  return{name:'CmsAppearanceControlPlane',data(){return{items:[],active:{},summary:{total:0,compatible:0,blocked:0,active:0},error:'',notice:'',loading:false,query:'',filter:'all',scope:'site',sitePackage:String(data().appearance?.sitePackage||'com_pinoox_cms')}},computed:{
    canActivate(){return hasAbility('themes.activate')},canCustomize(){return hasAbility('themes.customize')},
    siteActiveCount(){return this.active?.[this.sitePackage]?1:0},
    otherPackages(){return [...new Set(this.items.map(item=>item.package).filter(pkg=>pkg&&pkg!==this.sitePackage))].sort()},
    filtered(){const q=this.query.trim().toLowerCase();return this.items.filter(item=>{const healthy=(item.compatibility?.compatible!==false)&&(item.inheritance?.valid!==false);if(this.scope==='site'&&item.package!==this.sitePackage)return false;if(this.scope!=='site'&&this.scope!=='all'&&item.package!==this.scope)return false;if(this.filter==='compatible'&&!healthy)return false;if(this.filter==='blocked'&&healthy)return false;if(this.filter==='active'&&!this.isActive(item))return false;return !q||`${item.title||''} ${item.name||''} ${item.package||''} ${item.description||''}`.toLowerCase().includes(q)})},
  },mounted(){if(!document.getElementById('cms-appearance-center-css')){const s=document.createElement('style');s.id='cms-appearance-center-css';s.textContent=CSS;document.head.appendChild(s)}this.load()},methods:{
    async load(){this.loading=true;this.error='';try{const d=await api('/themes');this.items=d.items||[];this.active=d.active||{};this.summary=d.summary||{total:this.items.length,compatible:this.items.filter(x=>x.compatibility?.compatible!==false&&x.inheritance?.valid!==false).length,blocked:0,active:this.items.filter(x=>x.active).length}}catch(e){this.error=e.message}finally{this.loading=false}},
    healthy(x){return x.compatibility?.compatible!==false&&x.inheritance?.valid!==false},
    isSiteTheme(x){return String(x?.package||'')===this.sitePackage},
    isActive(x){const name=x?.name||x?.theme||x?.id;return Boolean(x?.active)||this.active?.[x?.package]===name},
    activeLabel(x){if(this.isActive(x))return this.isSiteTheme(x)?tr('appearance_page.site_theme_active'):tr('appearance_page.package_theme_active','',{package:x.package});return this.healthy(x)?tr('appearance_page.compatible'):tr('appearance_page.blocked')},
    issues(x){return [...(x.compatibility?.issues||[]),...(x.inheritance?.issues||[])]},
    async activate(x){if(!this.canActivate){this.error=tr('appearance_page.activate_denied','You do not have themes.activate permission.');return}if(!this.healthy(x)){this.error=tr('appearance_page.incompatible','This theme cannot be activated because it is incompatible or has a Parent issue.');return}const name=x.name||x.theme||x.id;if(!confirmFa(tr('appearance_page.activate_confirm','Activate theme “:name”?',{name:x.title||name})))return;this.error='';this.notice='';try{await api('/themes/activate',{method:'POST',body:{package:x.package,theme:name,context:null}});this.notice=tr('appearance_page.activated','Theme activated.');await this.load()}catch(e){this.error=e.message}},
    card(x){const name=x.name||x.theme||x.id,isActive=this.isActive(x),healthy=this.healthy(x),issues=this.issues(x),cover=safeCover(x.cover),requires=requirementLabel(x),chain=x.inheritance?.chain||[];return h('article',{class:`cms-theme-card${isActive?' active':''}${healthy?'':' blocked'}`,key:`${x.package}:${name}`},[
      cover?h('img',{class:'cms-theme-cover',src:cover,alt:x.title||name,loading:'lazy'}):h('div',{class:'cms-theme-cover cms-theme-no-preview'},[h('span',{},'▧'),h('small',{},tr('appearance_page.no_preview'))]),
      h('div',{class:'cms-theme-head'},[h('div',{},[h('strong',{},x.title||name),h('small',{style:{display:'block',opacity:.65}},this.isSiteTheme(x)?tr('appearance_page.nano_site_theme'):tr('appearance_page.app_theme','',{package:x.package}))]),h(LBadge,{label:this.activeLabel(x),severity:isActive?'success':healthy?'secondary':'danger'})]),
      h('p',{},x.description||tr('appearance_page.no_description','No description')),
      h('div',{class:'cms-theme-meta'},[h(LBadge,{label:`v${x.version||'—'}`,severity:'secondary'}),x.extends?.length?h(LBadge,{label:`Parent ${x.extends.length}`,severity:'secondary'}):h(LBadge,{label:'Standalone',severity:'secondary'}),healthy?h(LBadge,{label:tr('appearance_page.compatibility_ok','Compatibility OK'),severity:'success'}):h(LBadge,{label:tr('appearance_page.compatibility_blocked','Compatibility Blocked'),severity:'danger'})]),
      h('div',{class:'cms-theme-details'},[requires?h('span',{},tr('appearance_page.requirements','Requirements: :value',{value:requires})):null,chain.length?h('span',{},tr('appearance_page.inheritance','',{value:chain.join(' ← ')})):null,h('details',{},[h('summary',{},tr('appearance_page.technical_details')),h('code',{},x.reference||`${x.package}:${name}`)])]),
      issues.length?h('div',{class:'cms-theme-issues'},issues.map(i=>h('span',{},`• ${i}`))):null,
      h('div',{class:'cms-theme-actions'},[h(LButton,{label:isActive?tr('appearance_page.active_theme','Active theme'):tr('appearance_page.activate','Activate'),disabled:isActive||!healthy||!this.canActivate,onClick:()=>this.activate(x)}),isActive&&this.isSiteTheme(x)&&this.canCustomize?routeButton(h,LButton,tr('appearance_page.edit_site','Edit site'),'site-editor'):null,isActive&&this.isSiteTheme(x)?routeButton(h,LButton,tr('appearance_page.builder','Builder'),'builder'):null]),
    ])},
  },render(){return h(LPage,{title:tr('routes.appearance.title','Appearance'),description:tr('routes.appearance.lead','Pinoox-compatible Theme Center with compatibility and Parent Chain checks')},{default:()=>h('div',{class:'cms-appearance-center'},[
    message(h,this),
    h('div',{style:ui.grid},[h(LStatCard,{label:tr('appearance_page.installed','Installed themes'),value:String(this.summary.total??this.items.length)}),h(LStatCard,{label:tr('appearance_page.compatible','Compatible'),value:String(this.summary.compatible??0)}),h(LStatCard,{label:tr('appearance_page.blocked','Blocked'),value:String(this.summary.blocked??0)}),h(LStatCard,{label:tr('appearance_page.site_active'),value:String(this.siteActiveCount)})]),
    h(LPanel,{title:tr('appearance_page.design_operations','Design operations')},{default:()=>h('div',{style:ui.row},[routeButton(h,LButton,tr('appearance_page.builder','Builder'),'builder'),routeButton(h,LButton,tr('appearance_page.site_editor','Full Site Editor'),'site-editor')])}),
    h(LPanel,{title:tr('appearance_page.theme_center')},{default:()=>h('div',{style:ui.page},[h('div',{class:'cms-theme-toolbar'},[input(h,this.query,v=>this.query=v,'search',{placeholder:tr('appearance_page.search_placeholder','Name, package, or description')}),select(h,this.filter,v=>this.filter=v,[{value:'all',label:tr('appearance_page.all','All')},{value:'active',label:tr('appearance_page.active','Active')},{value:'compatible',label:tr('appearance_page.compatible','Compatible')},{value:'blocked',label:tr('appearance_page.blocked','Blocked')}]),select(h,this.scope,v=>this.scope=v,[{value:'site',label:tr('appearance_page.site_scope')},{value:'all',label:tr('appearance_page.all_apps_scope')},...this.otherPackages.map(pkg=>({value:pkg,label:tr('appearance_page.package_scope','',{package:pkg})}))]),h('div',{class:'grow'}),h(LButton,{label:tr('common.refresh','Refresh'),severity:'secondary',disabled:this.loading,onClick:this.load})]),h('small',{style:{opacity:.7}},tr('appearance_page.scope_help','',{package:this.sitePackage}))])}),
    this.loading?h('p',{},tr('appearance_page.loading','Loading…')):this.filtered.length?h('div',{class:'cms-theme-grid'},this.filtered.map(x=>this.card(x))):h('div',{class:'cms-theme-empty'},tr('appearance_page.empty_filter','No theme matches this filter.')),
  ])})}}
}
