import { api, data, ui, input, select, message, navigate, confirmFa, tr, brandName} from './common.mjs'

const CSS=`
.cms-site-editor{display:grid;gap:16px;direction:inherit}.cms-site-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.cms-site-template{border:1px solid var(--p-surface-200,#e5e7eb);border-radius:14px;padding:14px;display:grid;gap:10px;background:var(--p-surface-0,#fff)}.cms-site-template-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.cms-site-template small{opacity:.68}.cms-design-editor{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,360px);gap:14px;align-items:start}.cms-design-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cms-design-form label{display:grid;gap:5px;font-size:12px}.cms-design-preview{border:1px solid var(--p-surface-200,#e5e7eb);border-radius:16px;padding:18px;min-height:320px;display:grid;align-content:center;gap:12px}.cms-design-sample-button{display:inline-flex;padding:10px 16px;border-radius:10px;text-decoration:none;width:max-content}.cms-site-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.cms-site-status{display:flex;gap:6px;flex-wrap:wrap;align-items:center}@media(max-width:800px){.cms-design-editor{grid-template-columns:1fr}.cms-design-form{grid-template-columns:1fr}.cms-site-grid{grid-template-columns:1fr}}
`

function clone(v){return JSON.parse(JSON.stringify(v??{}))}
function getPath(obj,path,fallback=''){let cur=obj;for(const key of path.split('.')){if(cur==null||typeof cur!=='object'||!(key in cur))return fallback;cur=cur[key]}return cur??fallback}
function setPath(obj,path,value){const parts=path.split('.');let cur=obj;for(const key of parts.slice(0,-1)){if(!cur[key]||typeof cur[key]!=='object'||Array.isArray(cur[key]))cur[key]={};cur=cur[key]}cur[parts.at(-1)]=value}
function statusLabel(value){return ({published:tr('site_editor_page.published'),draft:tr('site_editor_page.draft'),'theme-fallback':tr('site_editor_page.theme_fallback')})[value]||value}
function templateLabel(type,key){if(type==='template_part')return key==='header'?tr('site_editor_page.header','Header'):tr('site_editor_page.footer','Footer');const labels={index:tr('site_editor_page.index','Index'),home:tr('site_editor_page.home','Home'),page:tr('site_editor_page.page','Page'),single:tr('site_editor_page.single','Single'),archive:tr('site_editor_page.archive','Archive'),taxonomy:tr('site_editor_page.taxonomy','Taxonomy'),search:tr('site_editor_page.search','Search'),'404':'404'};return labels[key]||key}
function localeOptions(){return [{value:'fa',label:tr('site_editor_page.fa','Persian')},{value:'en',label:tr('site_editor_page.en','English')},{value:'ar',label:tr('site_editor_page.ar','Arabic')}]}
function hasAbility(ability){const granted=data().currentUser?.abilities||[];return granted.includes('*')||granted.includes(ability)||granted.some(x=>typeof x==='string'&&x.endsWith('.*')&&ability.startsWith(x.slice(0,-1)))}

export function createComponent(host){
 const{h,LPage,LPanel,LButton,LBadge,LStatCard}=host
 return{name:'CmsFullSiteEditorCenter',data(){return{documents:[],summary:{total:0},pagination:{},locale:'fa',siteId:1,loading:false,error:'',notice:'',documentsLoaded:false,stylesLoaded:false,documentError:'',styleError:'',styleValue:{},styleVersion:null,styleDirty:false,styleLoading:false}},computed:{site(){return data().fullSiteEditor||{}},canCustomize(){return hasAbility('themes.customize')},templates(){return (this.site.templateKinds||['index','home','page','single','archive','taxonomy','search','404']).map(key=>({type:'template',key}))},parts(){return (this.site.templateParts||['header','footer']).map(key=>({type:'template_part',key}))},publishedCount(){return this.documents.filter(x=>x.status==='published').length},draftCount(){return this.documents.filter(x=>x.status==='draft').length}},mounted(){if(!document.getElementById('cms-site-editor-css')){const s=document.createElement('style');s.id='cms-site-editor-css';s.textContent=CSS;document.head.appendChild(s)}this.loadAll()},methods:{
  async loadAll(){this.loading=true;this.error='';this.notice='';const results=await Promise.allSettled([this.loadDocuments(),this.loadStyles()]);const failed=results.filter(x=>x.status==='rejected').length;if(failed)this.error=tr('site_editor_page.partial_load_failed','Some editor data could not be loaded.',{count:failed});this.loading=false},
  async loadDocuments(){this.documentError='';try{const result=await api(`/builder?site_id=${this.siteId}&locale=${encodeURIComponent(this.locale)}&limit=200`);this.documents=result.items||[];this.summary=result.summary||{};this.pagination=result.pagination||{};this.documentsLoaded=true}catch(e){this.documentsLoaded=false;this.documentError=e.message;throw e}},
  async loadStyles(){this.styleLoading=true;this.styleError='';try{const row=await api(`/settings/${encodeURIComponent('theme.design.overrides')}?scope_type=site&scope_id=${this.siteId}`);this.styleValue=clone(row.value||{});this.styleVersion=row.version||null;this.styleDirty=false;this.stylesLoaded=true}catch(e){this.stylesLoaded=false;this.styleError=e.message;throw e}finally{this.styleLoading=false}},
  doc(type,key){return this.documents.find(x=>x.target?.type===type&&x.target?.key===key&&x.target?.locale===this.locale)||null},
  status(type,key){const d=this.doc(type,key);return d?.status||'theme-fallback'},
  open(type,key){if(!this.documentsLoaded)return;const mode=this.doc(type,key)?'open':'create';navigate(`builder?type=${encodeURIComponent(type)}&key=${encodeURIComponent(key)}&locale=${encodeURIComponent(this.locale)}&site_id=${this.siteId}&${mode}=1`)},
  token(path,fallback=''){return getPath(this.styleValue,path,fallback)},
  setToken(path,value){setPath(this.styleValue,path,value);this.styleDirty=true},
  async saveStyles(){if(!this.canCustomize){this.error=tr('site_editor_page.customize_denied','You do not have themes.customize permission.');return}if(!this.stylesLoaded)return;this.error='';this.notice='';const submitted=JSON.stringify(this.styleValue),body=JSON.parse(submitted);try{const row=await api(`/settings/${encodeURIComponent('theme.design.overrides')}`,{method:'PUT',body:{value:body,scope_type:'site',scope_id:this.siteId,expected_version:this.styleVersion}});this.styleVersion=row.version||this.styleVersion;this.styleDirty=JSON.stringify(this.styleValue)!==submitted;this.notice=this.styleDirty?tr('site_editor_page.styles_saved_newer_draft','Saved the submitted styles; newer local changes remain unsaved.'):tr('site_editor_page.styles_saved','Global Styles were saved.')}catch(e){this.error=e.message}},
  async resetStyles(){if(!this.canCustomize){this.error=tr('site_editor_page.customize_denied','You do not have themes.customize permission.');return}if(!this.stylesLoaded||!confirmFa(tr('site_editor_page.reset_confirm','Reset all site design overrides to the theme defaults?')))return;this.error='';try{await api(`/settings/${encodeURIComponent('theme.design.overrides')}`,{method:'DELETE',body:{scope_type:'site',scope_id:this.siteId,expected_version:this.styleVersion}});await this.loadStyles();this.notice=tr('site_editor_page.overrides_removed','Design overrides were removed.')}catch(e){this.error=e.message}},
  styleControl(path,labelText,type='text'){const value=this.token(path,'');return h('label',{},[h('span',{},labelText),input(h,value,v=>this.setToken(path,type==='number'?String(v):v),type)])},
  renderTemplate(item){const d=this.doc(item.type,item.key),status=d?.status||'theme-fallback';return h('article',{class:'cms-site-template',key:`${item.type}:${item.key}`},[h('div',{class:'cms-site-template-head'},[h('div',{},[h('strong',{},templateLabel(item.type,item.key)),d?h('small',{style:{display:'block'}},tr('site_editor_page.override_version','',{id:d.id,version:d.version})):h('small',{style:{display:'block'}},tr('site_editor_page.theme_fallback_note')),h('details',{},[h('summary',{},tr('site_editor_page.technical_details')),h('code',{},`${item.type}:${item.key}`)])]),h(LBadge,{label:statusLabel(status),severity:status==='published'?'success':status==='draft'?'warning':'secondary'})]),h(LButton,{label:d?tr('site_editor_page.edit','Edit'):tr('site_editor_page.create_override','Create Override'),onClick:()=>this.open(item.type,item.key)})])},
 },render(){const bg=this.token('colors.background','#ffffff'),text=this.token('colors.text','#111827'),primary=this.token('colors.primary','#4f46e5'),body=this.token('fontFamilies.body','inherit'),baseSize=this.token('fontSizes.base','16px'),radius=this.token('radius.base','12px'),spacing=this.token('spacing.base','16px'),maxWidth=this.token('containers.content','720px'),unknown='—';return h(LPage,{title:tr('routes.site_editor.title','Full Site Editor'),description:tr('routes.site_editor.lead','Templates, Template Parts and global Design Tokens without modifying Theme files')},{default:()=>h('div',{class:'cms-site-editor'},[
  message(h,this),
  h('div',{class:'cms-site-toolbar'},[select(h,this.locale,async v=>{this.locale=v;try{await this.loadDocuments()}catch{}},localeOptions()),h(LButton,{label:tr('site_editor_page.refresh','Refresh'),severity:'secondary',onClick:this.loadAll}),h(LButton,{label:tr('site_editor_page.edit_home','Edit home page'),disabled:!this.documentsLoaded,onClick:()=>this.open('template','home')})]),
  h('div',{style:ui.grid},[h(LStatCard,{label:tr('site_editor_page.builder_documents','Builder documents'),value:this.documentsLoaded?String(this.summary.total??this.documents.length):unknown}),h(LStatCard,{label:tr('site_editor_page.published','Published'),value:this.documentsLoaded?String(this.publishedCount):unknown}),h(LStatCard,{label:tr('site_editor_page.draft','Draft'),value:this.documentsLoaded?String(this.draftCount):unknown}),h(LStatCard,{label:tr('site_editor_page.template_part','Template Part'),value:this.documentsLoaded?String(this.parts.length):unknown})]),
  this.documentError?h(LPanel,{title:tr('site_editor_page.documents_unavailable','Builder documents unavailable')},{default:()=>h('div',{role:'alert',style:ui.page},[h('p',{},this.documentError),h(LButton,{label:tr('site_editor_page.refresh','Refresh'),severity:'secondary',onClick:()=>this.loadDocuments().catch(()=>{})})])}):null,
  this.documentsLoaded?h(LPanel,{title:tr('site_editor_page.templates','Templates')},{default:()=>h('div',{class:'cms-site-grid'},this.templates.map(x=>this.renderTemplate(x)))}):null,
  this.documentsLoaded?h(LPanel,{title:tr('site_editor_page.parts','Template Parts')},{default:()=>h('div',{class:'cms-site-grid'},this.parts.map(x=>this.renderTemplate(x)))}):null,
  h(LPanel,{title:tr('site_editor_page.global_styles','Global Styles')},{default:()=>!this.stylesLoaded?h('div',{role:this.styleError?'alert':'status',style:ui.page},[h('strong',{},tr('site_editor_page.styles_unavailable','Design settings unavailable')),this.styleError?h('p',{},this.styleError):null,h(LButton,{label:tr('site_editor_page.refresh','Refresh'),severity:'secondary',onClick:()=>this.loadStyles().catch(()=>{})})]):h('div',{class:'cms-design-editor'},[
    h('div',{},[h('div',{class:'cms-design-form'},[
      this.styleControl('colors.primary',tr('site_editor_page.primary_color','Primary color'),'color'),this.styleControl('colors.background',tr('site_editor_page.background','Background'),'color'),this.styleControl('colors.text',tr('site_editor_page.text_color','Text color'),'color'),this.styleControl('fontFamilies.body',tr('site_editor_page.body_font','Body font')),this.styleControl('fontFamilies.heading',tr('site_editor_page.heading_font','Heading font')),this.styleControl('fontSizes.base',tr('site_editor_page.base_size','Base size')),this.styleControl('spacing.base',tr('site_editor_page.base_spacing','Base spacing')),this.styleControl('containers.content',tr('site_editor_page.content_width','Content width')),this.styleControl('radius.base',tr('site_editor_page.radius_base','Base radius')),
    ]),h('div',{style:{...ui.row,marginTop:'12px'}},[h(LButton,{label:tr('site_editor_page.save_styles','Save Global Styles'),disabled:!this.styleDirty||!this.canCustomize,onClick:this.saveStyles}),h(LButton,{label:tr('site_editor_page.reset_theme','Reset to theme'),severity:'secondary',disabled:!this.canCustomize,onClick:this.resetStyles}),this.styleDirty?h(LBadge,{label:tr('site_editor_page.unsaved','Unsaved'),severity:'warning'}):h(LBadge,{label:tr('site_editor_page.synced','Synced'),severity:'success'})])]),
    h('div',{class:'cms-design-preview',style:{background:bg,color:text,fontFamily:body,fontSize:baseSize,borderRadius:radius,padding:spacing,maxWidth}},[h('small',{},tr('site_editor_page.design_preview','Design Token preview')),h('h2',{style:{margin:0,fontFamily:this.token('fontFamilies.heading',body)}},brandName()),h('p',{style:{margin:0,lineHeight:1.8}},tr('site_editor_page.preview_note','Site overrides merge with Theme Design Tokens; Theme files are not modified.')),h('div',{style:ui.row},[h('button',{type:'button',disabled:true,'aria-disabled':'true',title:tr('site_editor_page.preview_only','Preview only'),class:'cms-design-sample-button',style:{background:primary,color:'#fff',border:0,borderRadius:radius}},tr('site_editor_page.sample_button','Sample button')),h(LBadge,{label:tr('site_editor_page.preview_only'),severity:'secondary'})])]),
  ])}),
  this.documentsLoaded&&(this.site.breakpointFallbacks||[]).length?h(LPanel,{title:tr('site_editor_page.responsive_contract','Responsive Contract')},{default:()=>h('div',{style:ui.page},[h('p',{},tr('site_editor_page.responsive_help')),h('div',{style:ui.row},(this.site.breakpointFallbacks||[]).map(bp=>h(LBadge,{label:tr('site_editor_page.breakpoint','',{id:bp.id,width:bp.minWidth}),severity:'secondary'})))])}):null,
 ])})}}
}
