<?php
declare(strict_types=1);
namespace App\com_pinoox_cms\Cms\ExtensionCenter\Package;
final readonly class ExtensionStagingStore
{
 public function __construct(private string $directory,private int $ttlSeconds=1800,private ExtensionPackageUploadPolicy $policy=new ExtensionPackageUploadPolicy()){}
 public function stage(string $temporaryPath,string $displayName,int $size):ExtensionStagingRecord
 { $r=$this->policy->validate($temporaryPath,$displayName,$size);$this->purgeExpired();$this->dir();$id='stage-'.bin2hex(random_bytes(16));$dir=$this->directory.'/'.$id;if(!mkdir($dir,0700,true)&&!is_dir($dir))throw new \RuntimeException('Unable to create extension staging directory.');$target=$dir.'/package.pinx';$in=fopen($r->localPath,'rb');$out=fopen($target,'xb');if($in===false||$out===false)throw new \RuntimeException('Unable to stage extension package.');try{$copied=stream_copy_to_stream($in,$out,$size+1);}finally{fclose($in);fclose($out);}if($copied!==$size){$this->remove($id);throw new \RuntimeException('Extension staging copy size mismatch.');}@chmod($target,0600);$sha=hash_file('sha256',$target);if(!is_string($sha)){ $this->remove($id);throw new \RuntimeException('Unable to hash staged package.');}$now=microtime(true);$rec=new ExtensionStagingRecord($id,$r->displayName,$target,$size,$sha,$now,$now+$this->ttlSeconds);$this->meta($rec);return$rec; }
 public function get(string $id):ExtensionStagingRecord
 { $this->id($id);$m=$this->directory.'/'.$id.'/stage.json';if(!is_file($m))throw new \RuntimeException('Extension staging package not found.');$d=json_decode((string)file_get_contents($m),true);if(!is_array($d))throw new \RuntimeException('Extension staging metadata is invalid.');$r=new ExtensionStagingRecord($id,(string)$d['display_name'],$this->directory.'/'.$id.'/package.pinx',(int)$d['size'],(string)$d['sha256'],(float)$d['created_at'],(float)$d['expires_at']);if(!$r->active()){$this->remove($id);throw new \RuntimeException('Extension staging package expired.');}if(!is_file($r->path)||is_link($r->path))throw new \RuntimeException('Staged package unavailable.');$sha=hash_file('sha256',$r->path);if(filesize($r->path)!==$r->size||!is_string($sha)||!hash_equals($r->sha256,$sha))throw new \RuntimeException('Staged package integrity check failed.');$this->policy->validate($r->path,$r->displayName,$r->size);return$r; }
 public function remove(string $id):void{$this->id($id);$this->tree($this->directory.'/'.$id);}
 public function purgeExpired():int{if(!is_dir($this->directory))return 0;$n=0;foreach(glob(rtrim($this->directory,'/\\').'/stage-*',GLOB_ONLYDIR)?:[] as$d){$m=$d.'/stage.json';$x=is_file($m)?json_decode((string)@file_get_contents($m),true):null;if(!is_array($x)||(float)($x['expires_at']??0)<=microtime(true)){$this->tree($d);$n++;}}return$n;}
 private function meta(ExtensionStagingRecord $r):void{$f=$this->directory.'/'.$r->id.'/stage.json';$j=json_encode(['display_name'=>$r->displayName,'size'=>$r->size,'sha256'=>$r->sha256,'created_at'=>$r->createdAt,'expires_at'=>$r->expiresAt],JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);if(file_put_contents($f,$j,LOCK_EX)===false){$this->remove($r->id);throw new \RuntimeException('Unable to persist staging metadata.');}@chmod($f,0600);}
 private function dir():void{if(!is_dir($this->directory)&&!mkdir($this->directory,0700,true)&&!is_dir($this->directory))throw new \RuntimeException('Unable to create staging root.');}
 private function id(string $id):void{if(preg_match('/^stage-[a-f0-9]{32}$/',$id)!==1)throw new \RuntimeException('Invalid staging id.');}
 private function tree(string $p):void{if(!file_exists($p)&&!is_link($p))return;if(is_file($p)||is_link($p)){@unlink($p);return;}foreach(scandir($p)?:[] as$n){if($n==='.'||$n==='..')continue;$this->tree($p.'/'.$n);}@rmdir($p);}
}
