<template>
  <LPage icon="palette" class="cms-appearance-page">
    <template #actions><div class="cms-card-actions"><LButton icon="panels-top-left" shape="rounded" @click="router.push('/builder')">{{ t('appearance_page.builder') }}</LButton><LButton icon="layout-template" variant="outline" shape="rounded" @click="router.push('/appearance/site-editor')">{{ t('appearance_page.site_editor') }}</LButton><LButton icon="refresh-cw" variant="outline" shape="rounded" :disabled="loading" @click="loadThemes">{{ t('common.refresh') }}</LButton></div></template>
    <div v-if="error" class="cms-alert cms-alert--danger">{{ error }}</div><div v-if="notice" class="cms-alert cms-alert--success">{{ notice }}</div>
    <div class="cms-stat-grid"><LStatCard :label="t('appearance_page.installed')" :value="String(summary.total||themes.length)" icon="palette"/><LStatCard :label="t('appearance_page.compatible')" :value="String(summary.compatible||0)" icon="badge-check"/><LStatCard :label="t('appearance_page.blocked')" :value="String(summary.blocked||0)" icon="shield-alert"/><LStatCard :label="t('appearance_page.active')" :value="String(summary.active||activeCount)" icon="circle-check"/></div>
    <LPanel><template #header>{{ t('appearance_page.theme_center') }}</template><div class="cms-control-form"><label>{{ t('appearance_page.search') }}<input v-model.trim="query" type="search" :placeholder="t('appearance_page.search_placeholder')"></label><label>{{ t('appearance_page.status') }}<select v-model="filter"><option value="all">{{ t('appearance_page.all') }}</option><option value="active">{{ t('appearance_page.active') }}</option><option value="compatible">{{ t('appearance_page.compatible') }}</option><option value="blocked">{{ t('appearance_page.blocked') }}</option></select></label></div></LPanel>
    <CmsPageState :state="loading ? 'loading' : filtered.length ? 'ready' : 'empty'" empty-icon="palette" :empty-title="t('appearance_page.empty_title')" :empty-message="t('appearance_page.empty_message')">
      <div class="cms-theme-grid"><article v-for="theme in filtered" :key="theme.id || `${theme.package}:${theme.name}`" class="cms-theme-card" :class="{active:isActive(theme),blocked:!healthy(theme)}">
        <div class="cms-theme-card__cover"><img v-if="safeCover(theme.cover)" :src="safeCover(theme.cover)" :alt="theme.title||theme.name"><LIcon v-else name="palette" :size="36"/></div>
        <div class="cms-theme-card__body"><div class="cms-card-actions"><strong>{{ theme.title || theme.name }}</strong><LBadge :severity="isActive(theme)?'success':healthy(theme)?'secondary':'danger'">{{ isActive(theme)?t('appearance_page.active'):healthy(theme)?t('appearance_page.compatible'):t('appearance_page.blocked') }}</LBadge></div><small>{{ theme.package }}:{{ theme.name }} · {{ theme.version || '—' }}</small><p>{{ theme.description || t('appearance_page.no_description') }}</p>
          <div class="cms-capability-cloud"><LBadge severity="secondary">v{{ theme.version||'—' }}</LBadge><LBadge severity="secondary">{{ theme.extends?.length ? `Parent ${theme.extends.length}` : 'Standalone' }}</LBadge><LBadge :severity="healthy(theme)?'success':'danger'">{{ healthy(theme)?t('appearance_page.compatibility_ok'):t('appearance_page.compatibility_blocked') }}</LBadge></div>
          <div v-if="theme.inheritance?.chain?.length" class="cms-muted">Inheritance: {{ theme.inheritance.chain.join(' ← ') }}</div><div v-if="requirements(theme)" class="cms-muted">{{ t('appearance_page.requirements',{value:requirements(theme)}) }}</div>
          <div v-if="issues(theme).length" class="cms-alert cms-alert--danger"><div v-for="issue in issues(theme)" :key="issue">• {{ issue }}</div></div>
          <div class="cms-card-actions"><LButton icon="check" size="sm" shape="rounded" :disabled="isActive(theme)||!healthy(theme)||!canActivate||busy===theme.id" @click="activate(theme)">{{ isActive(theme)?t('appearance_page.active_theme'):t('appearance_page.activate') }}</LButton><LButton v-if="isActive(theme)" icon="panels-top-left" size="sm" variant="outline" shape="rounded" @click="openBuilder(theme)">Builder</LButton><LButton v-if="isActive(theme)&&canCustomize" icon="layout-template" size="sm" variant="outline" shape="rounded" @click="router.push('/appearance/site-editor')">{{ t('appearance_page.edit_site') }}</LButton></div>
        </div></article></div>
    </CmsPageState>
  </LPage>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { useRouter } from 'vue-router';import { LBadge,LButton,LIcon,LPage,LPanel,LStatCard } from '@pinooxhq/luma/ui';import CmsPageState from '../../components/cms-page-state.vue';import { readAdminBootData } from '../../services/admin-provider.js';import { themeApi } from '../../services/cms-api.js';import { t } from '../../i18n/index.js'
const boot=readAdminBootData(),router=useRouter(),themes=ref([]),active=ref({}),summary=ref({total:0,compatible:0,blocked:0,active:0}),loading=ref(false),error=ref(''),notice=ref(''),busy=ref(''),query=ref(''),filter=ref('all');const abilities=boot.currentUser?.abilities||[];const hasAbility=a=>abilities.includes('*')||abilities.includes(a)||abilities.some(x=>typeof x==='string'&&x.endsWith('.*')&&a.startsWith(x.slice(0,-1)));const canActivate=computed(()=>hasAbility('themes.activate')),canCustomize=computed(()=>hasAbility('themes.customize')),activeCount=computed(()=>Object.keys(active.value||{}).length)
const healthy=t=>t.compatibility?.compatible!==false&&t.inheritance?.valid!==false;const issues=t=>[...(t.compatibility?.issues||[]),...(t.inheritance?.issues||[])];const safeCover=v=>/^(https?:\/\/|\/)/i.test(String(v||'').trim())?String(v).trim():'';const requirements=t=>Object.entries(t.cms?.requires||{}).map(([k,v])=>`${k} ${v}`).join(' · ');const filtered=computed(()=>{const q=query.value.toLowerCase();return themes.value.filter(t=>{if(filter.value==='active'&&!isActive(t))return false;if(filter.value==='compatible'&&!healthy(t))return false;if(filter.value==='blocked'&&healthy(t))return false;return !q||`${t.title||''} ${t.name||''} ${t.package||''} ${t.description||''}`.toLowerCase().includes(q)})})
async function loadThemes(){loading.value=true;error.value='';try{const r=await themeApi.list(),d=r.data||r;themes.value=d.items||[];active.value=d.active||{};summary.value=d.summary||summary.value}catch(e){error.value=e.message}finally{loading.value=false}}function isActive(t){return Boolean(t.active)||active.value?.[t.package]===t.name}async function activate(t){if(!canActivate.value||!healthy(t))return;if(!confirm(t('appearance_page.activate_confirm',{name:t.title||t.name})))return;busy.value=t.id||`${t.package}:${t.name}`;error.value='';notice.value='';try{await themeApi.activate(t.package,t.name,null);notice.value=t('appearance_page.activated');await loadThemes()}catch(e){error.value=e.message}finally{busy.value=''}}function openBuilder(t){router.push({path:'/builder',query:{type:'template',key:'home',theme:t.name,package:t.package}})}onMounted(loadThemes)
</script>
