<template>
  <LPage icon="layout-template" class="cms-site-editor-page">
    <template #actions><div class="cms-card-actions"><select v-model="locale" @change="loadDocuments"><option value="fa">{{ t('site_editor_page.fa') }}</option><option value="en">English</option><option value="ar">{{ t('site_editor_page.ar') }}</option></select><LButton variant="outline" :loading="loading" @click="loadAll">{{ t('site_editor_page.refresh') }}</LButton><LButton @click="openTarget('template','home')">{{ t('site_editor_page.edit_home') }}</LButton></div></template>
    <div v-if="error" class="cms-alert cms-alert--danger">{{ error }}</div><div v-if="notice" class="cms-alert cms-alert--success">{{ notice }}</div>
    <div class="cms-stat-grid"><LStatCard label="Builder Documents" :value="String(summary.total||documents.length)" icon="layout-template"/><LStatCard label="Published" :value="String(publishedCount)" icon="circle-check"/><LStatCard label="Draft" :value="String(draftCount)" icon="file-pen"/><LStatCard label="Template Parts" :value="String(parts.length)" icon="panel-top"/></div>
    <LPanel><template #header>{{ t('site_editor_page.templates') }}</template><div class="cms-card-grid"><article v-for="item in templates" :key="`${item.type}:${item.key}`" class="cms-list-card"><div><strong>{{ label(item) }}</strong><small>{{ item.type }}:{{ item.key }}</small><small v-if="doc(item)">#{{ doc(item).id }} · v{{ doc(item).version }}</small><small v-else>Theme hierarchy fallback</small></div><div class="cms-card-actions"><LBadge :severity="status(item)==='published'?'success':status(item)==='draft'?'warning':'secondary'">{{ status(item) }}</LBadge><LButton size="sm" variant="outline" @click="openTarget(item.type,item.key)">{{ doc(item) ? t('site_editor_page.edit') : t('site_editor_page.create_override') }}</LButton></div></article></div></LPanel>
    <LPanel><template #header>{{ t('site_editor_page.parts') }}</template><div class="cms-card-grid"><article v-for="item in parts" :key="`${item.type}:${item.key}`" class="cms-list-card"><div><strong>{{ label(item) }}</strong><small>{{ item.type }}:{{ item.key }}</small></div><div class="cms-card-actions"><LBadge :severity="status(item)==='published'?'success':status(item)==='draft'?'warning':'secondary'">{{ status(item) }}</LBadge><LButton size="sm" variant="outline" @click="openTarget(item.type,item.key)">{{ doc(item) ? t('site_editor_page.edit') : t('site_editor_page.create_override') }}</LButton></div></article></div></LPanel>
    <LPanel><template #header>Global Styles</template><div class="cms-control-form"><label>{{ t('site_editor_page.primary_color') }}<input v-model="tokens.colors.primary" type="color" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.background') }}<input v-model="tokens.colors.background" type="color" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.text_color') }}<input v-model="tokens.colors.text" type="color" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.body_font') }}<input v-model="tokens.fontFamilies.body" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.heading_font') }}<input v-model="tokens.fontFamilies.heading" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.base_size') }}<input v-model="tokens.fontSizes.base" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.base_spacing') }}<input v-model="tokens.spacing.base" :disabled="!canCustomize" @input="styleDirty=true"></label><label>{{ t('site_editor_page.content_width') }}<input v-model="tokens.containers.content" :disabled="!canCustomize" @input="styleDirty=true"></label><label>Radius<input v-model="tokens.radius.base" :disabled="!canCustomize" @input="styleDirty=true"></label></div><div class="cms-card-actions"><LButton :disabled="!canCustomize||!styleDirty" @click="saveStyles">{{ t('site_editor_page.save_styles') }}</LButton><LButton variant="outline" :disabled="!canCustomize" @click="resetStyles">{{ t('site_editor_page.reset_theme') }}</LButton><LBadge :severity="styleDirty?'warning':'success'">{{ styleDirty ? t('site_editor_page.unsaved') : t('site_editor_page.synced') }}</LBadge></div><div class="cms-design-preview" :style="previewStyle"><small>Design Token Preview</small><h2 :style="{fontFamily:tokens.fontFamilies.heading||tokens.fontFamilies.body||'inherit'}">{{ brand.name }}</h2><p>{{ t('site_editor_page.preview_note') }}</p><button :style="{background:tokens.colors.primary,color:'#fff',border:0,borderRadius:tokens.radius.base,padding:tokens.spacing.base}">{{ t('site_editor_page.sample_button') }}</button></div></LPanel>
    <LPanel><template #header>Responsive Contract</template><div class="cms-card-actions"><LBadge v-for="bp in site.breakpointFallbacks||[]" :key="bp.id" severity="secondary">{{ bp.id }}: {{ bp.minWidth }}</LBadge></div></LPanel>
  </LPage>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { useRouter } from 'vue-router';import { LBadge,LButton,LPage,LPanel,LStatCard } from '@pinooxhq/luma/ui';import { readAdminBootData } from '../../services/admin-provider.js';import { builderApi,cmsRequest } from '../../services/cms-api.js';import { cmsBrand, t } from '../../i18n/index.js'
const boot=readAdminBootData(),brand=cmsBrand(),site=boot.fullSiteEditor||{},router=useRouter(),documents=ref([]),summary=ref({}),locale=ref('fa'),siteId=ref(1),loading=ref(false),error=ref(''),notice=ref(''),styleVersion=ref(null),styleDirty=ref(false),tokens=reactive({colors:{primary:'#4f46e5',background:'#ffffff',text:'#111827'},fontFamilies:{body:'',heading:''},fontSizes:{base:'16px'},containers:{content:'720px'},radius:{base:'12px'},spacing:{base:'16px'}})
const abilities=boot.currentUser?.abilities||[];const hasAbility=a=>abilities.includes('*')||abilities.includes(a)||abilities.some(x=>typeof x==='string'&&x.endsWith('.*')&&a.startsWith(x.slice(0,-1)));const canCustomize=computed(()=>hasAbility('themes.customize'));const templates=computed(()=>Array.from(new Set(site.templateKinds||['index','home','page','single','archive','taxonomy','search','404'])).map(key=>({type:'template',key}))),parts=computed(()=>Array.from(new Set(site.templateParts||['header','footer'])).map(key=>({type:'template_part',key}))),publishedCount=computed(()=>documents.value.filter(x=>x.status==='published').length),draftCount=computed(()=>documents.value.filter(x=>x.status==='draft').length),previewStyle=computed(()=>({background:tokens.colors.background,color:tokens.colors.text,fontFamily:tokens.fontFamilies.body||'inherit',borderRadius:tokens.radius.base,padding:tokens.spacing.base,maxWidth:tokens.containers.content}))
function label(item){if(item.type==='template_part')return item.key==='header'?t('site_editor_page.header'):t('site_editor_page.footer');return ({index:'Index',home:t('site_editor_page.home'),page:t('site_editor_page.page'),single:t('site_editor_page.single'),archive:t('site_editor_page.archive'),taxonomy:'Taxonomy',search:t('site_editor_page.search'),'404':'404'})[item.key]||item.key}function doc(item){return documents.value.find(x=>x.target?.type===item.type&&x.target?.key===item.key&&x.target?.locale===locale.value)}function status(item){return doc(item)?.status||'theme-fallback'}function openTarget(type,key){router.push({path:'/builder',query:{type,key,locale:locale.value,site_id:siteId.value,open:1}})}function mergeTokens(v){for(const [root,obj] of Object.entries(v||{}))if(obj&&typeof obj==='object'&&!Array.isArray(obj)){tokens[root] ||= {};Object.assign(tokens[root],obj)}}
async function loadDocuments(){const b=await builderApi.list({site_id:siteId.value,locale:locale.value,limit:200});const bd=b.data||b;documents.value=bd.items||[];summary.value=bd.summary||{}}async function loadStyles(){const s=await cmsRequest(`/settings/theme.design.overrides?scope_type=site&scope_id=${siteId.value}`);const sr=s.data||s;styleVersion.value=sr.version||null;mergeTokens(sr.value||{});styleDirty.value=false}async function loadAll(){loading.value=true;error.value='';try{await Promise.all([loadDocuments(),loadStyles()])}catch(e){error.value=e.message}finally{loading.value=false}}async function saveStyles(){if(!canCustomize.value){error.value=t('site_editor_page.customize_denied');return}try{const r=await cmsRequest('/settings/theme.design.overrides',{method:'PUT',body:{value:JSON.parse(JSON.stringify(tokens)),scope_type:'site',scope_id:siteId.value,expected_version:styleVersion.value}});styleVersion.value=(r.data||r).version||styleVersion.value;styleDirty.value=false;notice.value=t('site_editor_page.styles_saved')}catch(e){error.value=e.message}}async function resetStyles(){if(!canCustomize.value)return;await cmsRequest('/settings/theme.design.overrides',{method:'DELETE',body:{scope_type:'site',scope_id:siteId.value,expected_version:styleVersion.value}});await loadStyles();notice.value=t('site_editor_page.overrides_removed')}
onMounted(loadAll)
</script>
