<?php
declare(strict_types=1);
namespace App\com_pinoox_cms\Controller\Api;
use App\com_pinoox_cms\Cms\Authorization\AuthorizationDeniedException;
use App\com_pinoox_cms\Cms\Media\{MediaInUseException,MediaKind,MediaUploadCandidate,MediaUploadValidationException,MediaValidationException};
use App\com_pinoox_cms\Cms\Runtime\{CmsApiResponse,CmsRuntimeErrorReporter,CmsRuntimeServices};
use Pinoox\Component\Kernel\Controller\ApiController;
use Pinoox\Component\Http\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
final class MediaApiController extends ApiController
{
 public function index(Request $request):JsonResponse{try{$site=$this->site($request->query->get('site_id',1));$raw=trim((string)$request->query->get('kind',''));$kind=$raw!==''?MediaKind::tryFrom($raw):null;if($raw!==''&&$kind===null)return CmsApiResponse::error('MEDIA_KIND_INVALID','Invalid media kind.',422);$page=CmsRuntimeServices::media()->library($site,$kind,$this->str($request->query->get('q')),max(1,min(100,(int)$request->query->get('limit',50))),max(0,(int)$request->query->get('offset',0)),CmsRuntimeServices::actorId());return CmsApiResponse::ok(['items'=>array_map(static fn($a)=>$a->toArray(),$page['items']),'site_id'=>$site,'summary'=>$page['summary'],'pagination'=>$page['pagination'],'upload_policy'=>$page['upload_policy'],'kinds'=>array_map(static fn(MediaKind $case):string=>$case->value,MediaKind::cases())]);}catch(AuthorizationDeniedException){return CmsApiResponse::error('FORBIDDEN','Media access is not permitted.',403);}catch(\Throwable $e){return CmsRuntimeErrorReporter::response($e,'MEDIA_LIST_FAILED','Media library could not be loaded.',500,['operation'=>'media.list']);}}
 public function upload(Request $request):JsonResponse{$file=$request->files->get('file');if(!$file instanceof UploadedFile)return CmsApiResponse::error('MEDIA_FILE_REQUIRED','A multipart file field named file is required.',422);if(!$file->isValid())return CmsApiResponse::error('MEDIA_UPLOAD_TRANSPORT_FAILED','Uploaded file did not pass HTTP upload validation.',422);try{$site=$this->site($request->request->get('site_id',1));$asset=CmsRuntimeServices::media()->upload(new MediaUploadCandidate($file->getPathname(),$file->getClientOriginalName(),$file->getClientMimeType()),$site,filter_var($request->request->get('public','1'),FILTER_VALIDATE_BOOL),trim((string)$request->request->get('title','')),trim((string)$request->request->get('alt','')),trim((string)$request->request->get('caption','')),trim((string)$request->request->get('description','')),[],CmsRuntimeServices::actorId(),$request->headers->get('X-Correlation-ID'));return CmsApiResponse::ok($asset->toArray(),201);}catch(AuthorizationDeniedException){return CmsApiResponse::error('FORBIDDEN','Media upload is not permitted.',403);}catch(MediaUploadValidationException|MediaValidationException|\InvalidArgumentException $e){return CmsApiResponse::error('MEDIA_VALIDATION_FAILED',$e->getMessage(),422);}catch(\Throwable $e){return CmsRuntimeErrorReporter::response($e,'MEDIA_UPLOAD_FAILED','Media upload could not be completed.',500,['operation'=>'media.upload']);}}
 public function show(int $id):JsonResponse{try{$details=CmsRuntimeServices::media()->details($id,CmsRuntimeServices::actorId());$asset=$details['asset']->toArray();$asset['usages']=array_map(static fn($u)=>$u->toArray(),$details['usages']);$asset['variants']=array_map(static fn($v)=>$v->toArray(),$details['variants']);$asset['in_use']=$details['in_use'];$asset['usage_count']=$details['usage_count'];$asset['variant_count']=$details['variant_count'];return CmsApiResponse::ok($asset);}catch(AuthorizationDeniedException){return CmsApiResponse::error('FORBIDDEN','Media access is not permitted.',403);}catch(MediaValidationException){return CmsApiResponse::error('MEDIA_NOT_FOUND','Media asset not found.',404);}catch(\Throwable $e){return CmsRuntimeErrorReporter::response($e,'MEDIA_READ_FAILED','Media asset could not be loaded.',500,['operation'=>'media.read']);}}
 public function update(Request $request,int $id):JsonResponse{try{$a=CmsRuntimeServices::media()->updateMetadata($id,$this->requestPayload($request),CmsRuntimeServices::actorId(),$request->headers->get('X-Correlation-ID'));return CmsApiResponse::ok($a->toArray());}catch(AuthorizationDeniedException){return CmsApiResponse::error('FORBIDDEN','Media update is not permitted.',403);}catch(MediaValidationException|\InvalidArgumentException $e){return CmsApiResponse::error('MEDIA_VALIDATION_FAILED',$e->getMessage(),422);}catch(\Throwable $e){return CmsRuntimeErrorReporter::response($e,'MEDIA_UPDATE_FAILED','Media asset could not be updated.',500,['operation'=>'media.update']);}}
 public function delete(Request $request,int $id):JsonResponse{try{$a=CmsRuntimeServices::media()->delete($id,CmsRuntimeServices::actorId(),$request->headers->get('X-Correlation-ID'));return CmsApiResponse::ok(['id'=>$a->id,'deleted'=>true]);}catch(AuthorizationDeniedException){return CmsApiResponse::error('FORBIDDEN','Media delete is not permitted.',403);}catch(MediaInUseException $e){return CmsApiResponse::error('MEDIA_IN_USE','Media asset is still in use.',409,['usages'=>array_map(static fn($u)=>$u->toArray(),$e->usages)]);}catch(\Throwable $e){return CmsRuntimeErrorReporter::response($e,'MEDIA_DELETE_FAILED','Media asset could not be deleted.',500,['operation'=>'media.delete']);}}
 private function site(mixed $v):int{$s=(int)$v;if($s!==1)throw new \InvalidArgumentException('Current CMS runtime supports site_id=1 only.');return$s;}
 private function str(mixed $v):?string{$v=trim((string)$v);return$v!==''?$v:null;}
 private function requestPayload(Request $r):array{try{$d=$r->toArray();}catch(\Throwable){$d=[];}return is_array($d)?$d:[];}
}
