<template>
  <LPage icon="blocks">
    <SafeModeBanner :safe-mode="data.safeMode" />
    <template #actions><div class="cms-card-actions"><LButton icon="refresh-cw" variant="outline" shape="rounded" :disabled="loading" @click="loadExtensions">{{ t('extensions_page.refresh') }}</LButton><LButton icon="package-plus" shape="rounded" @click="installOpen=!installOpen">{{ t('extensions_page.install_package') }}</LButton></div></template>
    <div class="cms-stat-grid"><LStatCard :label="t('extensions_page.installed')" :value="extensions.length" icon="blocks"/><LStatCard :label="t('extensions_page.active')" :value="activeCount" icon="circle-check"/><LStatCard :label="t('extensions_page.attention')" :value="problemCount" icon="triangle-alert"/><LStatCard label="API" :value="center.apiBound?'Bound':'Offline'" icon="network"/></div>
    <LPanel v-if="error" class="cms-inline-callout cms-inline-callout--danger" role="alert" aria-live="assertive"><strong>{{ t('extensions_page.operation_failed') }}</strong><p>{{ error }}</p></LPanel><p v-if="notice" class="cms-action-message" role="status" aria-live="polite">{{ notice }}</p>

    <LPanel v-if="installOpen" class="cms-control-panel"><template #header>{{ t('extensions_page.install_update') }}</template>
      <div class="cms-upload-zone"><input ref="fileInput" type="file" accept=".pinx,.zip" :aria-label="t('a11y.extension_package')" @change="inspectFile"><div><strong>{{ t('extensions_page.choose_package') }}</strong><small>{{ t('extensions_page.inspect_note', { max: maxUploadLabel }) }}</small></div></div>
      <div v-if="inspection" class="cms-extension-review">
        <div class="cms-definition-head">
          <div><strong>{{ reviewManifest.name || reviewManifest.identifier || inspection.stage?.name || t('extensions_page.package') }}</strong><small>{{ reviewManifest.identifier || '—' }} · {{ reviewManifest.version || '—' }}</small></div>
          <div class="cms-card-actions"><LBadge :severity="inspection.mode==='update'?'info':'success'">{{ inspection.mode==='update'?t('extensions_page.mode_update'):t('extensions_page.mode_install') }}</LBadge><LBadge :severity="decisionSeverity(reviewDecision)">{{ decisionLabel(reviewDecision) }}</LBadge></div>
        </div>
        <div class="cms-extension-review-grid">
          <article><strong>{{ t('extensions_page.trust') }}</strong><LBadge :severity="trustSeverity(reviewTrust.level)">{{ trustLabel(reviewTrust.level) }}</LBadge><small>{{ reviewTrust.assurance || t('extensions_page.no_assurance') }}</small></article>
          <article><strong>{{ t('extensions_page.dependencies') }}</strong><LBadge :severity="dependencyIssues.length?'danger':'success'">{{ dependencyIssues.length ? t('extensions_page.issue_count',{count:dependencyIssues.length}) : t('extensions_page.ready') }}</LBadge><small>{{ t('extensions_page.dependencies_help') }}</small></article>
          <article><strong>{{ t('extensions_page.permissions') }}</strong><LBadge :severity="riskSeverity(reviewRisk)">{{ riskLabel(reviewRisk) }}</LBadge><small>{{ t('extensions_page.permission_count',{count:reviewPermissions.length}) }}</small></article>
          <article><strong>{{ t('extensions_page.package_security') }}</strong><LBadge :severity="reviewSecurity?.ok===false?'danger':'success'">{{ reviewSecurity?.ok===false?t('extensions_page.blocked'):t('extensions_page.checked') }}</LBadge><small>{{ t('extensions_page.security_help') }}</small></article>
        </div>
        <div v-if="reviewWarnings.length||dependencyIssues.length" class="cms-extension-review-issues">
          <div v-for="warning in reviewWarnings" :key="`warning:${warning}`" class="cms-alert cms-alert--warning">{{ warning }}</div>
          <div v-for="issue in dependencyIssues" :key="`dependency:${issue.code}:${issue.target}`" class="cms-alert" :class="issue.blocking?'cms-alert--danger':'cms-alert--warning'"><strong>{{ issue.target || issue.code }}</strong><span>{{ issue.message }}</span></div>
        </div>
        <details v-if="reviewPermissions.length" class="cms-extension-review-permissions"><summary>{{ t('extensions_page.permission_details') }}</summary><div class="cms-stack"><article v-for="item in reviewPermissions" :key="item.permission" class="cms-list-card cms-list-card--wide"><div><strong>{{ item.permission }}</strong><small>{{ item.description || t('extensions_page.no_description') }}</small></div><LBadge :severity="riskSeverity(item.risk)">{{ riskLabel(item.risk) }}</LBadge></article></div></details>
        <label class="cms-toggle-row"><input v-model="approved" type="checkbox" :disabled="reviewDecision==='block'"><span>{{ t('extensions_page.review_approve') }}</span></label>
        <div class="cms-card-actions"><LButton icon="package-check" shape="rounded" :disabled="installing||!approved||reviewDecision==='block'" @click="executeInstall">{{ installing ? t('extensions_page.running') : inspection.mode==='update' ? t('extensions_page.run_update') : t('extensions_page.install_package') }}</LButton><LButton variant="outline" severity="neutral" shape="rounded" @click="clearInspection">{{ t('extensions_page.cancel') }}</LButton></div>
      </div>
    </LPanel>

    <div class="cms-control-filters"><input v-model="query" type="search" :placeholder="t('extensions_page.search_placeholder')" :aria-label="t('a11y.extension_search')"><select v-model="statusFilter" :aria-label="t('a11y.extension_status')"><option value="">{{ t('extensions_page.all_statuses') }}</option><option value="active">{{ t('extensions_page.active') }}</option><option value="inactive">{{ t('extensions_page.inactive') }}</option><option value="installed">{{ t('extensions_page.installed') }}</option><option value="failed">{{ t('extensions_page.failed') }}</option><option value="quarantined">{{ t('extensions_page.quarantined') }}</option><option value="incompatible">{{ t('extensions_page.incompatible') }}</option></select><select v-model="typeFilter" :aria-label="t('a11y.extension_type')"><option value="">{{ t('extensions_page.all_types') }}</option><option v-for="type in typeFilters" :key="type" :value="type">{{ typeLabel(type) }}</option></select></div>
    <CmsPageState :state="loading?'loading':filtered.length?'ready':'empty'" empty-icon="package-open" :empty-title="t('extensions_page.empty_title')" :empty-message="t('extensions_page.empty_message')">
      <div class="cms-mobile-only cms-extension-card-list"><article v-for="item in filtered" :key="item.id" class="cms-extension-card"><ExtensionCard :item="item"/></article></div>
      <LPanel flush bare class="cms-desktop-only"><LDataTable :value="filtered" paginator :rows="20" data-key="id"><Column field="name" :header="t('extensions_page.name')"/><Column :header="t('extensions_page.type')"><template #body="{data:row}">{{ typeLabel(row.type) }}</template></Column><Column field="version" :header="t('extensions_page.version')"/><Column :header="t('extensions_page.status')"><template #body="{data:row}"><LBadge :severity="statusSeverity(row.status)">{{ statusLabel(row.status) }}</LBadge></template></Column><Column :header="t('extensions_page.actions')"><template #body="{data:row}"><ExtensionActions :item="row"/></template></Column></LDataTable></LPanel>
    </CmsPageState>

    <LPanel><template #header>{{ t('extensions_page.platform_contract') }}</template><p class="cms-muted">{{ t('extensions_page.platform_note') }}</p></LPanel>
  </LPage>
</template>
<script setup>
import { computed,defineComponent,h,onMounted,ref } from 'vue';import Column from 'primevue/column';import { LBadge,LButton,LDataTable,LIcon,LPage,LPanel,LStatCard } from '@pinooxhq/luma/ui';import CmsPageState from '../../components/cms-page-state.vue';import SafeModeBanner from '../../components/safe-mode-banner.vue';import { readAdminBootData } from '../../services/admin-provider.js';import { extensionApi } from '../../services/cms-api.js';import { t } from '../../i18n/index.js'
const data=readAdminBootData(),center=data.extensionCenter;const extensions=ref([]),loading=ref(false),error=ref(''),notice=ref(''),query=ref(''),statusFilter=ref(''),typeFilter=ref(''),busy=ref({id:'',action:''}),installOpen=ref(false),inspection=ref(null),approved=ref(false),installing=ref(false),fileInput=ref(null);let inspectionRequest=0
const typeFilters=['core-module','module','plugin','integration','theme','admin-extension','block','block-package','driver','language-pack'];const maxUploadLabel=computed(()=>`${Math.round((center.upload.maxBytes||0)/1024/1024)} MB`);const activeCount=computed(()=>extensions.value.filter(i=>i.status==='active').length);const problemCount=computed(()=>extensions.value.reduce((n,i)=>n+(i.problems?.length||0)+(['failed','quarantined','incompatible'].includes(i.status)?1:0),0));const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return extensions.value.filter(i=>(!statusFilter.value||i.status===statusFilter.value)&&(!typeFilter.value||i.type===typeFilter.value)&&(!q||[i.name,i.id,i.package,i.publisher].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))});const reviewManifest=computed(()=>inspection.value?.review?.package?.manifest||{}),reviewTrust=computed(()=>inspection.value?.review?.package?.trust||{}),reviewDecision=computed(()=>inspection.value?.review?.review?.decision||'block'),dependencyIssues=computed(()=>inspection.value?.review?.review?.dependencies?.issues||[]),reviewPermissions=computed(()=>inspection.value?.review?.review?.permissions?.items||[]),reviewRisk=computed(()=>inspection.value?.review?.review?.permissions?.highest_risk||'low'),reviewWarnings=computed(()=>inspection.value?.review?.review?.warnings||[]),reviewSecurity=computed(()=>inspection.value?.review?.package?.security||null)
async function loadExtensions(){loading.value=true;error.value='';try{const r=await extensionApi.list();extensions.value=r.data?.items||[]}catch(e){error.value=e.message}finally{loading.value=false}}
async function inspectFile(e){const file=e.target.files?.[0];const request=++inspectionRequest;inspection.value=null;approved.value=false;error.value='';if(!file)return;try{const form=new FormData();form.append('file',file);const r=await extensionApi.inspect(form);if(request!==inspectionRequest)return;inspection.value=r.data}catch(err){if(request===inspectionRequest)error.value=err.message}}
async function executeInstall(){if(!inspection.value?.stage?.id)return;installing.value=true;error.value='';notice.value='';try{if(inspection.value.mode==='update'){const id=reviewManifest.value.identifier;if(!id)throw new Error(t('extensions_page.review_identity_missing'));await extensionApi.update(id,inspection.value.stage.id,true)}else await extensionApi.install(inspection.value.stage.id,true);notice.value=inspection.value.mode==='update'?t('extensions_page.installed_update'):t('extensions_page.installed_extension');clearInspection();installOpen.value=false;await loadExtensions()}catch(e){error.value=e.message}finally{installing.value=false}}
function clearInspection(){inspectionRequest++;inspection.value=null;approved.value=false;if(fileInput.value)fileInput.value.value=''}
async function op(id,actionName,action){busy.value={id,action:actionName};error.value='';notice.value='';try{await action();notice.value=t('extensions_page.operation_done');await loadExtensions()}catch(e){error.value=e.message}finally{busy.value={id:'',action:''}}}
function statusLabel(v){return({active:t('extensions_page.active'),inactive:t('extensions_page.inactive'),installed:t('extensions_page.installed'),failed:t('extensions_page.failed'),quarantined:t('extensions_page.quarantined'),incompatible:t('extensions_page.incompatible'),updating:t('extensions_page.updating')})[v]||v}function statusSeverity(v){if(v==='active')return'success';if(['failed','quarantined','incompatible'].includes(v))return'danger';if(v==='updating')return'warning';return'secondary'}function typeLabel(v){return({'core-module':t('extensions_page.type_core'),module:t('extensions_page.type_module'),plugin:t('extensions_page.type_plugin'),integration:t('extensions_page.type_integration'),theme:t('extensions_page.type_theme'),'admin-extension':t('extensions_page.type_admin'),block:t('extensions_page.type_block'),'block-package':t('extensions_page.type_block_pack'),driver:t('extensions_page.type_driver'),'language-pack':t('extensions_page.type_language')})[v]||v}function isCore(item){return item?.type==='core-module'}function decisionLabel(v){return({allow:t('extensions_page.decision_allow'),approval_required:t('extensions_page.decision_approval'),block:t('extensions_page.decision_block')})[v]||v}function decisionSeverity(v){return v==='allow'?'success':v==='approval_required'?'warning':'danger'}function trustLabel(v){return({verified:t('extensions_page.trust_verified'),unsigned:t('extensions_page.trust_unsigned'),invalid:t('extensions_page.trust_invalid'),unknown:t('extensions_page.trust_unknown')})[v]||v||t('extensions_page.trust_unknown')}function trustSeverity(v){return v==='verified'?'success':v==='invalid'?'danger':'warning'}function riskLabel(v){return({low:t('extensions_page.risk_low'),medium:t('extensions_page.risk_medium'),high:t('extensions_page.risk_high'),critical:t('extensions_page.risk_critical')})[v]||v||t('extensions_page.risk_low')}function riskSeverity(v){return v==='critical'||v==='high'?'danger':v==='medium'?'warning':'success'}
const ExtensionActions=defineComponent({props:{item:{type:Object,required:true}},setup(props){return()=>h('div',{class:'cms-card-actions cms-card-actions--wrap'},[
 isCore(props.item)&&props.item.status==='active'?h(LBadge,{severity:'info'},{default:()=>t('extensions_page.core_protected')}):props.item.status==='active'?h(LButton,{size:'sm',variant:'outline',shape:'rounded',disabled:busy.value.id===props.item.id,onClick:()=>op(props.item.id,'deactivate',()=>extensionApi.deactivate(props.item.id))},{default:()=>busy.value.id===props.item.id&&busy.value.action==='deactivate'?t('extensions_page.running'):t('extensions_page.deactivate')}):h(LButton,{size:'sm',shape:'rounded',disabled:busy.value.id===props.item.id,onClick:()=>op(props.item.id,'activate',()=>extensionApi.activate(props.item.id))},{default:()=>busy.value.id===props.item.id&&busy.value.action==='activate'?t('extensions_page.running'):t('extensions_page.activate')}),
 h(LButton,{size:'sm',variant:'outline',shape:'rounded',disabled:busy.value.id===props.item.id,onClick:()=>op(props.item.id,'repair',()=>extensionApi.repair(props.item.id))},{default:()=>busy.value.id===props.item.id&&busy.value.action==='repair'?t('extensions_page.running'):t('extensions_page.repair')}),
 !isCore(props.item)?h(LButton,{size:'sm',variant:'outline',severity:'danger',shape:'rounded',disabled:busy.value.id===props.item.id,onClick:()=>window.confirm(t('extensions_page.uninstall_confirm',{id:props.item.name||props.item.id}))&&op(props.item.id,'uninstall',()=>extensionApi.uninstall(props.item.id))},{default:()=>busy.value.id===props.item.id&&busy.value.action==='uninstall'?t('extensions_page.running'):t('extensions_page.delete')}):null
])}})
const ExtensionCard=defineComponent({props:{item:{type:Object,required:true}},setup(props){return()=>h('div',{},[h('div',{class:'cms-extension-card__head'},[h('div',{},[h('strong',{},props.item.name||props.item.package||props.item.id),h('small',{},props.item.publisher||''),h('details',{class:'cms-muted'},[h('summary',{},t('extensions_page.technical_details')),h('code',{},props.item.id)])]),h(LBadge,{severity:statusSeverity(props.item.status)},{default:()=>statusLabel(props.item.status)})]),h('div',{class:'cms-extension-badges'},[h(LBadge,{severity:'secondary'},{default:()=>typeLabel(props.item.type)}),isCore(props.item)?h(LBadge,{severity:'info'},{default:()=>t('extensions_page.core_protected')}):null,props.item.trust?h(LBadge,{severity:trustSeverity(props.item.trust.level)},{default:()=>trustLabel(props.item.trust.level)}):null]),h(ExtensionActions,{item:props.item})])}})
onMounted(loadExtensions)
</script>
