<template>
  <LPage icon="blocks">
    <SafeModeBanner :safe-mode="data.safeMode" />
    <template #actions><div class="cms-card-actions"><LButton icon="refresh-cw" variant="outline" shape="rounded" :disabled="loading" @click="loadExtensions">{{ t('extensions_page.refresh') }}</LButton><LButton icon="package-plus" shape="rounded" @click="installOpen=!installOpen">{{ t('extensions_page.install_package') }}</LButton></div></template>
    <div class="cms-stat-grid"><LStatCard :label="t('extensions_page.installed')" :value="extensions.length" icon="blocks"/><LStatCard :label="t('extensions_page.active')" :value="activeCount" icon="circle-check"/><LStatCard :label="t('extensions_page.attention')" :value="problemCount" icon="triangle-alert"/><LStatCard label="API" :value="center.apiBound?'Bound':'Offline'" icon="network"/></div>
    <LPanel v-if="error" class="cms-inline-callout cms-inline-callout--danger" role="alert" aria-live="assertive"><strong>{{ t('extensions_page.operation_failed') }}</strong><p>{{ error }}</p></LPanel>

    <LPanel v-if="installOpen" class="cms-control-panel"><template #header>{{ t('extensions_page.install_update') }}</template>
      <div class="cms-upload-zone"><input ref="fileInput" type="file" accept=".pinx,.zip" :aria-label="t('a11y.extension_package')" @change="inspectFile"><div><strong>{{ t('extensions_page.choose_package') }}</strong><small>{{ t('extensions_page.inspect_note', { max: maxUploadLabel }) }}</small></div></div>
      <div v-if="inspection" class="cms-extension-review"><div class="cms-definition-head"><strong>{{ inspection.review?.manifest?.name || inspection.review?.manifest?.id || inspection.stage?.name || 'Package' }}</strong><LBadge :severity="inspection.mode==='update'?'info':'success'">{{ inspection.mode==='update'?'Update':'Install' }}</LBadge></div><pre class="cms-code-preview">{{ reviewSummary }}</pre><label class="cms-toggle-row"><input v-model="approved" type="checkbox"><span>{{ t('extensions_page.review_approve') }}</span></label><div class="cms-card-actions"><LButton icon="package-check" shape="rounded" :disabled="installing||!approved" @click="executeInstall">{{ installing ? t('extensions_page.running') : inspection.mode==='update' ? t('extensions_page.run_update') : t('extensions_page.install_package') }}</LButton><LButton variant="outline" severity="neutral" shape="rounded" @click="clearInspection">{{ t('extensions_page.cancel') }}</LButton></div></div>
    </LPanel>

    <div class="cms-control-filters"><input v-model="query" type="search" :placeholder="t('extensions_page.search_placeholder')" :aria-label="t('a11y.extension_search')"><select v-model="statusFilter" :aria-label="t('a11y.extension_status')"><option value="">{{ t('extensions_page.all_statuses') }}</option><option value="active">{{ t('extensions_page.active') }}</option><option value="inactive">{{ t('extensions_page.inactive') }}</option><option value="installed">{{ t('extensions_page.installed') }}</option><option value="failed">{{ t('extensions_page.failed') }}</option><option value="quarantined">{{ t('extensions_page.quarantined') }}</option><option value="incompatible">{{ t('extensions_page.incompatible') }}</option></select><select v-model="typeFilter" :aria-label="t('a11y.extension_type')"><option value="">{{ t('extensions_page.all_types') }}</option><option v-for="type in typeFilters" :key="type" :value="type">{{ typeLabel(type) }}</option></select></div>
    <CmsPageState :state="loading?'loading':filtered.length?'ready':'empty'" empty-icon="package-open" :empty-title="t('extensions_page.empty_title')" :empty-message="t('extensions_page.empty_message')">
      <div class="cms-mobile-only cms-extension-card-list"><article v-for="item in filtered" :key="item.id" class="cms-extension-card"><ExtensionCard :item="item"/></article></div>
      <LPanel flush bare class="cms-desktop-only"><LDataTable :value="filtered" paginator :rows="20" data-key="id"><Column field="name" :header="t('extensions_page.name')"/><Column :header="t('extensions_page.type')"><template #body="{data:row}">{{ typeLabel(row.type) }}</template></Column><Column field="version" :header="t('extensions_page.version')"/><Column :header="t('extensions_page.status')"><template #body="{data:row}"><LBadge :severity="statusSeverity(row.status)">{{ statusLabel(row.status) }}</LBadge></template></Column><Column :header="t('extensions_page.actions')"><template #body="{data:row}"><ExtensionActions :item="row"/></template></Column></LDataTable></LPanel>
    </CmsPageState>

    <LPanel><template #header>{{ t('extensions_page.platform_contract') }}</template><p class="cms-muted">{{ t('extensions_page.platform_note') }}</p></LPanel>
  </LPage>
</template>
<script setup>
import { computed,defineComponent,h,onMounted,ref } from 'vue';import Column from 'primevue/column';import { LBadge,LButton,LDataTable,LIcon,LPage,LPanel,LStatCard } from '@pinooxhq/luma/ui';import CmsPageState from '../../components/cms-page-state.vue';import SafeModeBanner from '../../components/safe-mode-banner.vue';import { readAdminBootData } from '../../services/admin-provider.js';import { extensionApi } from '../../services/cms-api.js';import { t } from '../../i18n/index.js'
const data=readAdminBootData(),center=data.extensionCenter;const extensions=ref([]),loading=ref(false),error=ref(''),query=ref(''),statusFilter=ref(''),typeFilter=ref(''),busy=ref(''),installOpen=ref(false),inspection=ref(null),approved=ref(false),installing=ref(false),fileInput=ref(null)
const typeFilters=['core-module','module','plugin','integration','theme','admin-extension','block','block-package','driver','language-pack'];const maxUploadLabel=computed(()=>`${Math.round((center.upload.maxBytes||0)/1024/1024)} MB`);const activeCount=computed(()=>extensions.value.filter(i=>i.status==='active').length);const problemCount=computed(()=>extensions.value.reduce((n,i)=>n+(i.problems?.length||0)+(['failed','quarantined','incompatible'].includes(i.status)?1:0),0));const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return extensions.value.filter(i=>(!statusFilter.value||i.status===statusFilter.value)&&(!typeFilter.value||i.type===typeFilter.value)&&(!q||[i.name,i.id,i.publisher].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))});const reviewSummary=computed(()=>JSON.stringify({trust:inspection.value?.review?.trust||inspection.value?.review?.inspection?.trust||null,compatibility:inspection.value?.review?.compatibility||null,dependencies:inspection.value?.review?.dependencies||null,permissions:inspection.value?.review?.permissions||null},null,2))
async function loadExtensions(){loading.value=true;error.value='';try{const r=await extensionApi.list();extensions.value=r.data?.items||[]}catch(e){error.value=e.message}finally{loading.value=false}}
async function inspectFile(e){const file=e.target.files?.[0];if(!file)return;error.value='';inspection.value=null;approved.value=false;try{const form=new FormData();form.append('file',file);const r=await extensionApi.inspect(form);inspection.value=r.data}catch(err){error.value=err.message}}
async function executeInstall(){if(!inspection.value?.stage?.id)return;installing.value=true;error.value='';try{await extensionApi.install(inspection.value.stage.id,true);clearInspection();installOpen.value=false;await loadExtensions()}catch(e){error.value=e.message}finally{installing.value=false}}
function clearInspection(){inspection.value=null;approved.value=false;if(fileInput.value)fileInput.value.value=''}
async function op(id,action){busy.value=id;error.value='';try{await action();await loadExtensions()}catch(e){error.value=e.message}finally{busy.value=''}}
function statusLabel(v){return({active:t('extensions_page.active'),inactive:t('extensions_page.inactive'),installed:t('extensions_page.installed'),failed:t('extensions_page.failed'),quarantined:t('extensions_page.quarantined'),incompatible:t('extensions_page.incompatible'),updating:t('extensions_page.updating')})[v]||v}function statusSeverity(v){if(v==='active')return'success';if(['failed','quarantined','incompatible'].includes(v))return'danger';if(v==='updating')return'warning';return'secondary'}function typeLabel(v){return({'core-module':'Core Module',module:'Module',plugin:'Plugin',integration:'Integration',theme:'Theme','admin-extension':'Admin Extension',block:'Block','block-package':'Block Pack',driver:'Driver','language-pack':'Language Pack'})[v]||v}
const ExtensionActions=defineComponent({props:{item:{type:Object,required:true}},setup(props){return()=>h('div',{class:'cms-card-actions cms-card-actions--wrap'},[
 props.item.status==='active'?h(LButton,{size:'sm',variant:'outline',shape:'rounded',disabled:busy.value===props.item.id,onClick:()=>op(props.item.id,()=>extensionApi.deactivate(props.item.id))},{default:()=> t('extensions_page.deactivate')}):h(LButton,{size:'sm',shape:'rounded',disabled:busy.value===props.item.id,onClick:()=>op(props.item.id,()=>extensionApi.activate(props.item.id))},{default:()=> t('extensions_page.activate')}),
 h(LButton,{size:'sm',variant:'outline',shape:'rounded',disabled:busy.value===props.item.id,onClick:()=>op(props.item.id,()=>extensionApi.repair(props.item.id))},{default:()=> 'Repair'}),
 props.item.type!=='core-module'?h(LButton,{size:'sm',variant:'outline',severity:'danger',shape:'rounded',disabled:busy.value===props.item.id,onClick:()=>window.confirm(t('extensions_page.uninstall_confirm',{id:props.item.id}))&&op(props.item.id,()=>extensionApi.uninstall(props.item.id))},{default:()=> 'Uninstall'}):null
])}})
const ExtensionCard=defineComponent({props:{item:{type:Object,required:true}},setup(props){return()=>h('div',{},[h('div',{class:'cms-extension-card__head'},[h('div',{},[h('strong',{},props.item.name),h('small',{},props.item.id)]),h(LBadge,{severity:statusSeverity(props.item.status)},{default:()=>statusLabel(props.item.status)})]),h('div',{class:'cms-extension-badges'},[h(LBadge,{severity:'secondary'},{default:()=>typeLabel(props.item.type)}),props.item.trust?h(LBadge,{severity:props.item.trust.level==='verified'?'success':'warning'},{default:()=>props.item.trust.level}):null]),h(ExtensionActions,{item:props.item})])}})
onMounted(loadExtensions)
</script>
