<?php

return [
    'package' => 'com_pinoox_cms',
    'enable' => true,
    'sys-app' => true,
    'hidden' => false,
    'dock' => true,
    'open' => 'app-view',
    'icon' => '@layout-dashboard',
    'name' => 'cms',
    'title' => 'NanoPino',
    'description' => 'NanoPino — next-generation CMS and extension platform for Pinoox.',
    'theme' => 'cms-admin',
    'lang' => 'fa',
    'date' => 'jalali',
    'developer' => 'NanoPino Project',
    'version-name' => '0.23.74',
    'version-code' => 2374,
    'minpin' => 232,
    'boot' => true,
    'boot-global' => false,
    'router' => [
        'routes' => ['routes/web.php'],
    ],
    'frontend' => [
        'stack' => 'vue',
        'profile' => 'spa',
        'entry' => 'src/main.js',
        'entries' => ['src/main.js'],
        'mount' => '#app',
        'manifest' => 'dist/.vite/manifest.json',
        'dev' => [
            'prefer_manifest' => true,
        ],
    ],
    'database' => [
        // Reuse the native Pinoox platform connection while enforcing a valid
        // MySQL/MariaDB table engine when the host exposes DB_ENGINE as empty.
        // Non-MySQL drivers ignore this connection option.
        'use' => 'platform',
        // Keep the native MySQL/MariaDB engine guarantee without forcing the
        // local DevDB/SQLite connection through the MySQL app clone path.
        'engine' => in_array(
            strtolower((string) env('DB_CONNECTION', '')),
            ['mysql', 'mariadb'],
            true,
        ) ? 'InnoDB' : null,
    ],
    'table' => [
        'prefix' => 'cms_',
    ],
    'transport' => [
        'user' => 'platform',
        'access' => 'platform',
        'file_storage' => 'platform',
    ],
    'access' => [
        'enabled' => true,
        'super_roles' => ['admin', 'superadmin'],
        // Explicit admin/superadmin roles are required; platform-scoped users
        // must not receive implicit super access from their app association.
        'platform_super' => false,
        'groups' => [],
    ],
    'cms' => [
        'schema' => 1,
        'extension_type' => 'core-module',
        'publisher' => 'pinoox-cms-project',
        'brand' => [
            'name' => 'NanoPino',
            'legacy_package' => 'com_pinoox_cms',
            'compatibility_mode' => 'non-breaking-brand-rename',
        ],
        'requires' => [
            'php' => '>=8.2',
            'pincore' => '>=3.14.0',
            'luma' => '>=0.4.10',
        ],
        'dependencies' => [],
        'optional_dependencies' => [],
        'conflicts' => [],
        'provides' => [
            'cms.kernel',
            'cms.extension-platform',
            'cms.admin-platform',
        ],
        'replaces' => [],
        'permissions' => [],
        'services' => [
            'content',
            'taxonomy',
            'public-taxonomy',
            'media',
            'authorization',
            'settings',
            'identity',
            'extensions',
            'hooks',
            'theme',
            'blocks',
            'builder',
            'revision',
            'audit',
            'updates',
            'recovery',
            'search',
            'cache',
            'queue',
            'storage',
            'security',
            'performance',
            'health',
            'logging',
            'support-diagnostics',
            'developer-sdk',
            'extension-sdk-logical-migrations',
            'extension-package-preflight',
            'documentation',
            'release-candidate',
            'source-first-release-tooling',
            'source-first-update-rc11',
            'installability-preflight-r15',
            'native-pinx-artifact-audit-r15',
            'runtime-api',
            'runtime-api-completeness',
            'admin-control-plane',
            'controller-compatibility',
            'response-contract',
            'schema-health',
            'installer-schema-repair',
            'runtime-error-correlation',
            'native-auth-context',
            'logical-table-contract',
            'legacy-double-prefix-repair',
            'settings-center',
            'operational-health-center',
            'content-admin-center',
            'taxonomy-management-center',
            'public-taxonomy-archives',
            'public-site-context',
            'public-navigation',
            'public-host-routing',
            'public-domain-registry',
            'public-domain-registry-fail-closed',
            'schema-driven-content-editor',
            'content-bulk-operations',
            'content-scheduling-ui',
            'content-scheduled-publisher',
            'editorial-production-workflow',
            'content-batch-hydration',
            'content-query-projections',
            'content-cursor-pagination',
            'media-admin-center',
            'media-library-pagination',
            'media-upload-policy',
            'media-usage-safety',
            'media-upload-pincore-compat',
            'users-capabilities-center',
            'identity-list-pagination',
            'rbac-visibility',
            'self-lockout-guards',
            'visual-builder-center',
            'full-site-editor-center',
            'global-styles-center',
            'builder-document-inventory',
            'builder-pointer-dnd',
            'builder-idle-autosave',
            'builder-undo-coalescing',
            'builder-diagnostic-boundary',
            'theme-compatibility-center',
            'theme-inheritance-gate',
            'runtime-reliability-layer',
            'kernel-compatibility-fix',
            'support-bundle-runtime-kernel',
            'nanopino-brand',
            'pinoox-query-probe',
            'content-ownership-boundary',
            'author-assignment-authorization',
            'strict-same-origin-csrf',
            'security-hardening-r5',
        ],
        'service_registry' => [
            'schema' => 1,
            'source' => 'resources/release/service-registry-parity-v1.json',
            'count' => 91,
        ],
        'capabilities' => [],
        'abilities' => [],
        'hooks' => [],
        'admin' => [
            'theme' => 'cms-admin',
            'framework' => 'luma',
            'rtl' => true,
            'mobile_first' => true,
        ],
        'api' => [
            'base' => '/api/v1/cms',
            'version' => 'v1',
        ],
        'frontend' => [
            'stack' => 'vue',
            'admin_theme' => 'cms-admin',
            'build_required' => true,
        ],
    ],
    'public' => [
        // Public routes read one validated context instead of duplicating
        // site/locale defaults in each controller action.
        'site_id' => 1,
        'locale' => 'fa',
        // Optional exact host map for multi-site deployments. When populated,
        // every public request must match one of these hosts.
        'hosts' => [],
    ],
    'pinx' => [
        'type' => 'app',
        'minpin' => 232,
    ],
    'build' => [
        'exclude' => [
            'tests',
            'docs',
            '.git',
            '.github',
            'node_modules',
            'theme/cms-admin/src',
            'theme/cms-admin/tests',
            'theme/cms-admin/node_modules',
            'theme/cms-admin/package.json',
            'theme/cms-admin/package-lock.json',
            'theme/cms-admin/vite.config.js',
            'theme/cms-admin/vite.config.mjs',
            'theme/cms-admin/build-linux.sh',
            'theme/cms-admin/build-windows.ps1',
            'theme/cms-admin/run-tests.mjs',
            'theme/cms-admin/verify-dist.mjs',
            'theme/cms-admin/source-fingerprint.mjs',
            'theme/cms-admin/runtime-fingerprint.mjs',
            'theme/cms-admin/repair-existing-builder.sh',
            'theme/cms-admin/README-FA.md',
            // Prototype tooling is development-only and must not ship in a
            // production CMS package or widen the runtime attack surface.
            'prototype',
            'prototype/**',
            'Controller/PrototypeController.php',
        ],
        'include' => [
            // The generic docs exclude pattern also matches resources/docs;
            // release evidence must remain inside the distributable artifact.
            'resources/docs',
            'resources/docs/**',
        ],
    ],
];
