<?php

return [
    'package' => 'com_pinoox_cms',
    'enable' => true,
    'sys-app' => true,
    'hidden' => false,
    'dock' => true,
    'open' => 'app-view',
    'icon' => '@layout-dashboard',
    'name' => 'cms',
    'title' => 'NanoPino',
    'description' => 'NanoPino — next-generation CMS and extension platform for Pinoox.',
    'theme' => 'cms-admin',
    'lang' => 'fa',
    'date' => 'jalali',
    'developer' => 'NanoPino Project',
    'version-name' => '0.23.28',
    'version-code' => 2328,
    'minpin' => 205,
    'boot' => true,
    'boot-global' => false,
    'router' => [
        'routes' => ['routes/web.php'],
    ],
    'frontend' => [
        'stack' => 'vue',
        'profile' => 'spa',
        'entry' => 'src/main.js',
        'entries' => ['src/main.js'],
        'mount' => '#app',
        'manifest' => 'dist/.vite/manifest.json',
        'dev' => [
            'prefer_manifest' => true,
        ],
    ],
    'database' => [
        // Reuse the native Pinoox platform connection while enforcing a valid
        // MySQL/MariaDB table engine when the host exposes DB_ENGINE as empty.
        // Non-MySQL drivers ignore this connection option.
        'use' => 'platform',
        'engine' => 'InnoDB',
    ],
    'table' => [
        'prefix' => 'cms_',
    ],
    'transport' => [
        'user' => 'platform',
        'access' => 'platform',
        'file_storage' => 'platform',
    ],
    'access' => [
        'enabled' => true,
        'super_roles' => ['admin', 'superadmin'],
        'platform_super' => true,
        'groups' => [],
    ],
    'cms' => [
        'schema' => 1,
        'extension_type' => 'core-module',
        'publisher' => 'pinoox-cms-project',
        'brand' => [
            'name' => 'NanoPino',
            'legacy_package' => 'com_pinoox_cms',
            'compatibility_mode' => 'non-breaking-brand-rename',
        ],
        'requires' => [
            'php' => '>=8.2',
            'pincore' => '>=3.8.15',
            'luma' => '>=0.4.10',
        ],
        'dependencies' => [],
        'optional_dependencies' => [],
        'conflicts' => [],
        'provides' => [
            'cms.kernel',
            'cms.extension-platform',
            'cms.admin-platform',
        ],
        'replaces' => [],
        'permissions' => [],
        'services' => [
            'content',
            'media',
            'authorization',
            'settings',
            'extensions',
            'hooks',
            'theme',
            'blocks',
            'builder',
            'revision',
            'search',
            'cache',
            'queue',
            'storage',
            'security',
            'performance',
            'health',
            'logging',
            'support-diagnostics',
            'developer-sdk',
            'extension-sdk-logical-migrations',
            'extension-package-preflight',
            'documentation',
            'release-candidate',
            'runtime-api',
            'runtime-api-completeness',
            'content-batch-hydration',
            'content-query-projections',
            'content-cursor-pagination',
            'pinoox-query-probe',
            'content-ownership-boundary',
            'author-assignment-authorization',
            'strict-same-origin-csrf',
            'security-hardening-r5',
            'nanopino-brand',
            'admin-control-plane',
            'media-admin-center',
            'users-capabilities-center',
            'visual-builder-center',
            'full-site-editor-center',
            'global-styles-center',
            'builder-document-inventory',
            'theme-inheritance-gate',
            'theme-compatibility-center',
            'builder-undo-coalescing',
            'builder-idle-autosave',
            'builder-pointer-dnd',
            'source-first-release-tooling',
            'source-first-update-rc11',
        ],
        'capabilities' => [],
        'abilities' => [],
        'hooks' => [],
        'admin' => [
            'theme' => 'cms-admin',
            'framework' => 'luma',
            'rtl' => true,
            'mobile_first' => true,
        ],
        'api' => [
            'base' => '/api/v1/cms',
            'version' => 'v1',
        ],
        'frontend' => [
            'stack' => 'vue',
            'admin_theme' => 'cms-admin',
            'build_required' => true,
        ],
    ],
    'pinx' => [
        'type' => 'app',
        'minpin' => 205,
    ],
    'build' => [
        'exclude' => ['tests', 'docs', '.git', '.github', 'node_modules'],
    ],
];
